### ISSUE TITLE
Does not work: -o parameter is absent

### ISSUE THREAD

**Issue by dobromyslov** [japaric/swap-ld#4]
Does not work any longer.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cortex-m-rt-ld-0.1.1\src\main.rs:29:25
```

https://github.com/japaric/cortex-m-rt-ld/blob/4f80d36eaa21890fb686e1ddb0368b60a7163343/src/main.rs#L23

Seems it can't find `-o` parameter which, I presume, was expected to be on the command line in the past.

**Comment by japaric** [comment]
This tool is no longer maintained. Use flip-link instead: https://github.com/knurling-rs/flip-link
